//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeTrackingMouseV03Lib.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EyeTrackingMouseV03Lib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///    Stump-based 20x20 frontal eye detector.
        ///    Created by Shameem Hameed (http://umich.edu/~shameem)
        ///
        ///////////////////////////////////////////////////////////////////////////////////////////
        ///
        ///  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///
        ///  By downloading, copying, installing or using the software you agree to this license.
        ///  If you do not agree to this license, do not download, install,
        ///  copy or use the software.
        ///
        ///
        ///                        Intel License Agr [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcasade_eye_tree_eyeglasses {
            get {
                return ResourceManager.GetString("haarcasade_eye_tree_eyeglasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;classifier_DuvarSaati type_id=&quot;opencv-haar-classifier&quot;&gt;
        ///  &lt;size&gt;
        ///    30 30&lt;/size&gt;
        ///  &lt;stages&gt;
        ///    &lt;_&gt;
        ///      &lt;!-- stage 0 --&gt;
        ///      &lt;trees&gt;
        ///        &lt;_&gt;
        ///          &lt;!-- tree 0 --&gt;
        ///          &lt;_&gt;
        ///            &lt;!-- root node --&gt;
        ///            &lt;feature&gt;
        ///              &lt;rects&gt;
        ///                &lt;_&gt;
        ///                  11 0 10 10 -1.&lt;/_&gt;
        ///                &lt;_&gt;
        ///                  11 5 10 5 2.&lt;/_&gt;&lt;/rects&gt;
        ///              &lt;tilted&gt;0&lt;/tilted&gt;&lt;/feature&gt;
        ///            &lt;threshold&gt;0 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_clock {
            get {
                return ResourceManager.GetString("haarcascade_clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///    Stump-based 20x20 frontal eye detector.
        ///    Created by Shameem Hameed (http://umich.edu/~shameem)
        ///
        ///////////////////////////////////////////////////////////////////////////////////////////
        ///
        ///  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///
        ///  By downloading, copying, installing or using the software you agree to this license.
        ///  If you do not agree to this license, do not download, install,
        ///  copy or use the software.
        ///
        ///
        ///                        Intel License Agr [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_eye {
            get {
                return ResourceManager.GetString("haarcascade_eye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///    Tree-based 20x20 frontal eye detector with better handling of eyeglasses.
        ///    Created by Shameem Hameed (http://umich.edu/~shameem)
        ///
        ///////////////////////////////////////////////////////////////////////////////////////////
        ///
        ///  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///
        ///  By downloading, copying, installing or using the software you agree to this license.
        ///  If you do not agree to this license, do not download, install,
        ///  copy or use the software.
        ///
        ///
        ///        [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_eye_tree_eyeglasses {
            get {
                return ResourceManager.GetString("haarcascade_eye_tree_eyeglasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///    Stump-based 20x20 gentle adaboost frontal face detector.
        ///    Created by Rainer Lienhart.
        ///
        ///////////////////////////////////////////////////////////////////////////////////////////
        ///
        ///  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///
        ///  By downloading, copying, installing or using the software you agree to this license.
        ///  If you do not agree to this license, do not download, install,
        ///  copy or use the software.
        ///
        ///
        ///                        Intel License Agreement
        ///   [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_frontalface_alt {
            get {
                return ResourceManager.GetString("haarcascade_frontalface_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///    Stump-based 20x20 gentle adaboost frontal face detector.
        ///    This detector uses tree of stage classifiers instead of a cascade
        ///    Created by Rainer Lienhart.
        ///
        ///////////////////////////////////////////////////////////////////////////////////////////
        ///
        ///  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///
        ///  By downloading, copying, installing or using the software you agree to this license.
        ///  If you do not agree to this license, do not download, install,
        ///  copy or  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_frontalface_alt_tree {
            get {
                return ResourceManager.GetString("haarcascade_frontalface_alt_tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///    Tree-based 20x20 gentle adaboost frontal face detector.
        ///    Created by Rainer Lienhart.
        ///
        ///////////////////////////////////////////////////////////////////////////////////////////
        ///
        ///  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///
        ///  By downloading, copying, installing or using the software you agree to this license.
        ///  If you do not agree to this license, do not download, install,
        ///  copy or use the software.
        ///
        ///
        ///                        Intel License Agreement
        ///    [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_frontalface_alt2 {
            get {
                return ResourceManager.GetString("haarcascade_frontalface_alt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///    Stump-based 24x24 discrete(?) adaboost frontal face detector.
        ///    Created by Rainer Lienhart.
        ///
        ///////////////////////////////////////////////////////////////////////////////////////////
        ///
        ///  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///
        ///  By downloading, copying, installing or using the software you agree to this license.
        ///  If you do not agree to this license, do not download, install,
        ///  copy or use the software.
        ///
        ///
        ///                        Intel License Agreeme [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_frontalface_default {
            get {
                return ResourceManager.GetString("haarcascade_frontalface_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///   14x28 fullbody detector (see the detailed description below). 
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license, do not download, install,
        ///|   copy or use the software.
        ///|
        ///| Copyright (c) 2004, Hannes Kruppa and Bernt Sch [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_fullbody {
            get {
                return ResourceManager.GetString("haarcascade_fullbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!----------------------------------------------------------------------------
        ///  45x11 Eye pair detector computed with 7000 positive samples
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license, do not download, install,
        ///| [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_iris {
            get {
                return ResourceManager.GetString("haarcascade_iris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///    Tree-based 20x20 left eye detector.
        ///    The detector is trained by 6665 positive samples from FERET, VALID and BioID face databases. 
        ///    Created by Shiqi Yu (http://yushiqi.cn/research/eyedetection).
        ///
        ///////////////////////////////////////////////////////////////////////////////////////////
        ///
        ///  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///
        ///  By downloading, copying, installing or using the software you agree to this license.
        ///  If you do not agree to this lic [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_lefteye_2splits {
            get {
                return ResourceManager.GetString("haarcascade_lefteye_2splits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///   19x23 lowerbody detector (see the detailed description below). 
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license, do not download, install,
        ///|   copy or use the software.
        ///|
        ///| Copyright (c) 2004, Hannes Kruppa and Bernt Sc [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_lowerbody {
            get {
                return ResourceManager.GetString("haarcascade_lowerbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///  45x11 Eye pair detector computed with 7000 positive samples
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license, do not download, install,
        ///|   copy or use the software.
        ///|
        ///| Copyright (c) 2006, Modesto Castrillon-Santana (IUS [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_mcs_eyepair_big {
            get {
                return ResourceManager.GetString("haarcascade_mcs_eyepair_big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;parojos_7000pos_15000neg_45x11 type_id=&quot;opencv-haar-classifier&quot;&gt;
        ///  &lt;size&gt;
        ///    45 11&lt;/size&gt;
        ///  &lt;stages&gt;
        ///    &lt;_&gt;
        ///      &lt;trees&gt;
        ///        &lt;_&gt;
        ///          &lt;_&gt;
        ///            &lt;feature&gt;
        ///              &lt;rects&gt;
        ///                &lt;_&gt;
        ///                  7 3 30 3 -1.&lt;/_&gt;
        ///                &lt;_&gt;
        ///                  17 3 10 3 3.&lt;/_&gt;&lt;/rects&gt;
        ///              &lt;tilted&gt;0&lt;/tilted&gt;&lt;/feature&gt;
        ///            &lt;threshold&gt;0.1012997999787331&lt;/threshold&gt;
        ///            &lt;left_val&gt;-0.7954636812210083&lt;/lef [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_mcs_eyepair_big_test {
            get {
                return ResourceManager.GetString("haarcascade_mcs_eyepair_big_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///  22x5 Eye pair detector computed with 7000 positive samples
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license, do not download, install,
        ///|   copy or use the software.
        ///|
        ///| Copyright (c) 2006, Modesto Castrillon-Santana (IUSI [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_mcs_eyepair_small {
            get {
                return ResourceManager.GetString("haarcascade_mcs_eyepair_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!----------------------------------------------------------------------------
        ///  12x20 Left ear (in the image) detector computed with 5000 positive and 15000
        ///  negative samples
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license, d [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_mcs_leftear {
            get {
                return ResourceManager.GetString("haarcascade_mcs_leftear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///  18x12 Left eye (in the image) detector computed with 7000 positive samples
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license, do not download, install,
        ///|   copy or use the software.
        ///|
        ///| Copyright (c) 2006, Modesto Castrill [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_mcs_lefteye {
            get {
                return ResourceManager.GetString("haarcascade_mcs_lefteye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///  25x15 Mouth detector computed with 7000 positive samples
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license, do not download, install,
        ///|   copy or use the software.
        ///|
        ///| Copyright (c) 2006, Modesto Castrillon-Santana (IUSIAN [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_mcs_mouth {
            get {
                return ResourceManager.GetString("haarcascade_mcs_mouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///  18x15 Nose detector computed with 7000 positive samples
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license, do not download, install,
        ///|   copy or use the software.
        ///|
        ///| Copyright (c) 2008, Modesto Castrillon-Santana (IUSIANI [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_mcs_nose {
            get {
                return ResourceManager.GetString("haarcascade_mcs_nose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!----------------------------------------------------------------------------
        ///  12x20 Right ear (in the image) detector computed with 5000 positive and 15000
        ///  negative samples
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license,  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_mcs_rightear {
            get {
                return ResourceManager.GetString("haarcascade_mcs_rightear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///  18x12 Right eye (in the image) detector computed with 7000 positive samples
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license, do not download, install,
        ///|   copy or use the software.
        ///|
        ///| Copyright (c) 2006, Modesto Castril [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_mcs_righteye {
            get {
                return ResourceManager.GetString("haarcascade_mcs_righteye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///  22x20 Head and shoulders detector 
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license, do not download, install,
        ///|   copy or use the software.
        ///|
        ///| Copyright (c) 2006, Modesto Castrillon-Santana (IUSIANI, University of
        ///| Las [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_mcs_upperbody {
            get {
                return ResourceManager.GetString("haarcascade_mcs_upperbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///    20x20 profile face detector.
        ///    Contributed by David Bradley from Princeton University.
        ///
        ///////////////////////////////////////////////////////////////////////////////////////////
        ///
        ///  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///
        ///  By downloading, copying, installing or using the software you agree to this license.
        ///  If you do not agree to this license, do not download, install,
        ///  copy or use the software.
        ///
        ///
        ///                        Intel License Agreement
        ///   [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_profileface {
            get {
                return ResourceManager.GetString("haarcascade_profileface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///    Tree-based 20x20 right eye detector.
        ///    The detector is trained by 6665 positive samples from FERET, VALID and BioID face databases. 
        ///    Created by Shiqi Yu (http://yushiqi.cn/research/eyedetection).
        ///
        ///////////////////////////////////////////////////////////////////////////////////////////
        ///
        ///  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///
        ///  By downloading, copying, installing or using the software you agree to this license.
        ///  If you do not agree to this li [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_righteye_2splits {
            get {
                return ResourceManager.GetString("haarcascade_righteye_2splits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///   22x18 upperbody detector (see the detailed description below). 
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license, do not download, install,
        ///|   copy or use the software.
        ///|
        ///| Copyright (c) 2004, Hannes Kruppa and Bernt Sc [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string haarcascade_upperbody {
            get {
                return ResourceManager.GetString("haarcascade_upperbody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;cascade&gt;
        ///  &lt;stageType&gt;BOOST&lt;/stageType&gt;
        ///  &lt;featureType&gt;HOG&lt;/featureType&gt;
        ///  &lt;height&gt;96&lt;/height&gt;
        ///  &lt;width&gt;48&lt;/width&gt;
        ///  &lt;stageParams&gt;
        ///    &lt;boostType&gt;GAB&lt;/boostType&gt;
        ///    &lt;minHitRate&gt;9.9500000476837158e-01&lt;/minHitRate&gt;
        ///    &lt;maxFalseAlarm&gt;5.0000000000000000e-01&lt;/maxFalseAlarm&gt;
        ///    &lt;weightTrimRate&gt;9.4999999999999996e-01&lt;/weightTrimRate&gt;
        ///    &lt;maxDepth&gt;1&lt;/maxDepth&gt;
        ///    &lt;maxWeakCount&gt;100&lt;/maxWeakCount&gt;&lt;/stageParams&gt;
        ///  &lt;featureParams&gt;
        ///    &lt;maxCatCount&gt;0&lt;/maxCatCount&gt;
        ///    &lt;featSi [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string hogcascade_pedestrians {
            get {
                return ResourceManager.GetString("hogcascade_pedestrians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!--
        ///number of positive samples 3000
        ///number of negative samples 1500
        ///--&gt;
        ///&lt;opencv_storage&gt;
        ///&lt;cascade type_id=&quot;opencv-cascade-classifier&quot;&gt;
        ///  &lt;stageType&gt;BOOST&lt;/stageType&gt;
        ///  &lt;featureType&gt;LBP&lt;/featureType&gt;
        ///  &lt;height&gt;24&lt;/height&gt;
        ///  &lt;width&gt;24&lt;/width&gt;
        ///  &lt;stageParams&gt;
        ///    &lt;boostType&gt;GAB&lt;/boostType&gt;
        ///    &lt;minHitRate&gt;0.9950000047683716&lt;/minHitRate&gt;
        ///    &lt;maxFalseAlarm&gt;0.5000000000000000&lt;/maxFalseAlarm&gt;
        ///    &lt;weightTrimRate&gt;0.9500000000000000&lt;/weightTrimRate&gt;
        ///    &lt;maxDepth&gt;1&lt;/maxDepth&gt;        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string lbpcascade_frontalface {
            get {
                return ResourceManager.GetString("lbpcascade_frontalface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!----------------------------------------------------------------------------
        ///  18x12 Left eye (in the image) detector computed with 7000 positive samples
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license, do not downlo [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LEye {
            get {
                return ResourceManager.GetString("LEye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;!----------------------------------------------------------------------------
        ///  18x12 Right eye (in the image) detector computed with 7000 positive samples
        ///
        /////////////////////////////////////////////////////////////////////////////
        ///| Contributors License Agreement
        ///| IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
        ///|   By downloading, copying, installing or using the software you agree 
        ///|   to this license.
        ///|   If you do not agree to this license, do not downl [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string REye {
            get {
                return ResourceManager.GetString("REye", resourceCulture);
            }
        }
    }
}
